### ISSUE TITLE
is there any way to control the max number of tags?

### ISSUE THREAD

**Issue by jblotus** [jbouzekri/SculpinTagCloudBundle#1]
right now it looks like all of them are being rendered. i would like to limit this somehow.

**Comment by jbouzekri** [comment]
Hi,

You are right, there is no way right now to do that but it is simple to implement with the strategy configuration.

I will add this evening a strategy to limit the number of tag in the cloud.

Thanks for pointing that out.
I will keep you posted on the updates.

Have a nice day

**Comment by jbouzekri** [comment]
I created a 1.1 release version with the function.

You have to change the configuration : 

``` yml
jb_tag_cloud:
    max_number: 5
    strategies:
        - jb_sculpin.tag_cloud.strategy.shuffle
        - jb_sculpin.tag_cloud.strategy.percent_size
        - jb_sculpin.tag_cloud.strategy.max_number
```

This will limit the number of displayed tag to 5 after applying the shuffle and percent size strategy.

Do not hesitate if you meet any issue
